services:
  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "4321:80"

  backend:
    working_dir: /app
    image: node:22-alpine
    ports:
      - "1234:3000"
    volumes:
      - ./backend:/app
    command: npm run start
